import '../../features/topic_selection/data/models/topic.dart';

class AppTopics {
  static const List<Topic> all = [
    // Technology
    Topic(id: 't1', title: 'The impact of AI on employment', category: 'Technology', hint: 'Consider both job losses and new opportunities created'),
    Topic(id: 't2', title: 'Should social media platforms be regulated?', category: 'Technology', hint: 'Think about free speech vs. harm reduction'),
    Topic(id: 't3', title: 'The future of remote work', category: 'Technology', hint: 'Benefits for workers, challenges for companies'),
    Topic(id: 't4', title: 'Are smartphones making us less intelligent?', category: 'Technology', hint: 'Look at memory, attention span, and dependency'),
    Topic(id: 't5', title: 'The ethics of data collection', category: 'Technology', hint: 'Privacy trade-offs in a connected world'),
    Topic(id: 't6', title: 'Should autonomous vehicles be on public roads?', category: 'Technology', hint: 'Safety statistics vs. public trust'),
    Topic(id: 't7', title: 'The future of virtual and augmented reality', category: 'Technology', hint: 'Education, entertainment, and social impact'),
    Topic(id: 't8', title: 'Biometric data: convenience or invasion of privacy?', category: 'Technology', hint: 'Face ID, fingerprints, health data'),
    Topic(id: 't9', title: 'Should children have smartphones before age 13?', category: 'Technology', hint: 'Safety, development, and social pressure'),
    Topic(id: 't10', title: 'The role of technology in modern education', category: 'Technology', hint: 'Online learning, tablets, and AI tutors'),
    Topic(id: 't11', title: 'Cybersecurity threats in the digital age', category: 'Technology', hint: 'Personal and national security implications'),
    Topic(id: 't12', title: 'Will electric vehicles replace petrol cars?', category: 'Technology', hint: 'Infrastructure, cost, and environmental factors'),
    Topic(id: 't13', title: 'The impact of algorithms on what we read and watch', category: 'Technology', hint: 'Filter bubbles and recommendation engines'),
    Topic(id: 't14', title: 'Telemedicine: the future of healthcare?', category: 'Technology', hint: 'Accessibility vs. quality of care'),
    Topic(id: 't15', title: 'Open source software and its impact on innovation', category: 'Technology', hint: 'Collaboration vs. commercial incentives'),
    Topic(id: 't16', title: 'Should AI be allowed to make legal decisions?', category: 'Technology', hint: 'Bias, accountability, and due process'),
    Topic(id: 't17', title: 'The pros and cons of working from home permanently', category: 'Technology', hint: 'Productivity, isolation, and work-life balance'),
    Topic(id: 't18', title: 'Digital literacy: a basic skill for the 21st century', category: 'Technology', hint: 'Should it be taught in every school?'),
    Topic(id: 't19', title: 'The dark side of online gaming', category: 'Technology', hint: 'Addiction, toxicity, and mental health'),
    Topic(id: 't20', title: 'Blockchain beyond cryptocurrency', category: 'Technology', hint: 'Supply chain, voting, identity verification'),

    // Society
    Topic(id: 's1', title: 'The importance of mental health awareness', category: 'Society', hint: 'Stigma reduction and access to support'),
    Topic(id: 's2', title: 'Should voting be mandatory?', category: 'Society', hint: 'Civic duty vs. freedom of choice'),
    Topic(id: 's3', title: 'The effects of social media on teenagers', category: 'Society', hint: 'Self-esteem, comparison, and cyberbullying'),
    Topic(id: 's4', title: 'Gender equality in the workplace', category: 'Society', hint: 'Pay gaps, representation, and cultural barriers'),
    Topic(id: 's5', title: 'Should university education be free?', category: 'Society', hint: 'Funding models and access to opportunity'),
    Topic(id: 's6', title: 'The role of media in shaping public opinion', category: 'Society', hint: 'Bias, sensationalism, and responsibility'),
    Topic(id: 's7', title: 'Urban vs rural living: which is better?', category: 'Society', hint: 'Opportunity, community, and quality of life'),
    Topic(id: 's8', title: 'The impact of celebrity culture on society', category: 'Society', hint: 'Values, aspirations, and role models'),
    Topic(id: 's9', title: 'The prison system: rehabilitation or punishment?', category: 'Society', hint: 'Recidivism rates and purpose of incarceration'),
    Topic(id: 's10', title: 'Animal rights and factory farming', category: 'Society', hint: 'Ethics of food production at scale'),
    Topic(id: 's11', title: 'Should the death penalty be abolished?', category: 'Society', hint: 'Justice, deterrence, and human rights'),
    Topic(id: 's12', title: 'Immigration and its impact on host countries', category: 'Society', hint: 'Economic contributions and cultural integration'),
    Topic(id: 's13', title: 'The digital divide and inequality', category: 'Society', hint: 'Who is left behind in the digital economy?'),
    Topic(id: 's14', title: 'Homelessness: a societal failure?', category: 'Society', hint: 'Causes, solutions, and shared responsibility'),
    Topic(id: 's15', title: 'Body image and the media', category: 'Society', hint: 'Unrealistic standards and mental health'),
    Topic(id: 's16', title: 'Should religion be kept out of politics?', category: 'Society', hint: 'Separation of church and state'),
    Topic(id: 's17', title: 'The role of sports in national identity', category: 'Society', hint: 'Unity, pride, and soft power'),
    Topic(id: 's18', title: 'The gig economy and workers\' rights', category: 'Society', hint: 'Flexibility vs. job security and benefits'),
    Topic(id: 's19', title: 'How poverty affects educational outcomes', category: 'Society', hint: 'Breaking the cycle of disadvantage'),
    Topic(id: 's20', title: 'The impact of gentrification on communities', category: 'Society', hint: 'Development benefits vs. displacement costs'),

    // Personal Growth
    Topic(id: 'pg1', title: 'The importance of failure in achieving success', category: 'Personal Growth', hint: 'What specific failures have taught you the most?'),
    Topic(id: 'pg2', title: 'How reading changes your perspective', category: 'Personal Growth', hint: 'Fiction, non-fiction, and empathy'),
    Topic(id: 'pg3', title: 'The power of morning routines', category: 'Personal Growth', hint: 'Habits that set the tone for the day'),
    Topic(id: 'pg4', title: 'Overcoming the fear of public speaking', category: 'Personal Growth', hint: 'Techniques and mindset shifts that help'),
    Topic(id: 'pg5', title: 'The value of stepping outside your comfort zone', category: 'Personal Growth', hint: 'Growth happens at the edge of discomfort'),
    Topic(id: 'pg6', title: 'The role of mentorship in career development', category: 'Personal Growth', hint: 'Finding and being a good mentor'),
    Topic(id: 'pg7', title: 'How to stay motivated when things get hard', category: 'Personal Growth', hint: 'Intrinsic vs. extrinsic motivation'),
    Topic(id: 'pg8', title: 'The importance of setting boundaries', category: 'Personal Growth', hint: 'At work and in relationships'),
    Topic(id: 'pg9', title: 'The impact of gratitude on mental wellbeing', category: 'Personal Growth', hint: 'Science-backed benefits of a gratitude practice'),
    Topic(id: 'pg10', title: 'The difference between confidence and arrogance', category: 'Personal Growth', hint: 'How self-assurance can be humble'),
    Topic(id: 'pg11', title: 'How adversity builds character', category: 'Personal Growth', hint: 'Examples from history and personal experience'),
    Topic(id: 'pg12', title: 'The art of saying no', category: 'Personal Growth', hint: 'Why it\'s one of the hardest and most important skills'),
    Topic(id: 'pg13', title: 'Why emotional intelligence matters more than IQ', category: 'Personal Growth', hint: 'Self-awareness, empathy, and relationships'),
    Topic(id: 'pg14', title: 'How to deal with criticism constructively', category: 'Personal Growth', hint: 'Separating feedback from personal attack'),
    Topic(id: 'pg15', title: 'Building resilience in uncertain times', category: 'Personal Growth', hint: 'Mindset strategies for navigating change'),
    Topic(id: 'pg16', title: 'The value of lifelong learning', category: 'Personal Growth', hint: 'Curiosity as a career and life advantage'),
    Topic(id: 'pg17', title: 'The importance of curiosity', category: 'Personal Growth', hint: 'How staying curious drives progress'),
    Topic(id: 'pg18', title: 'Learning from people very different from you', category: 'Personal Growth', hint: 'Breaking out of your echo chamber'),
    Topic(id: 'pg19', title: 'Why silence can be a powerful communication tool', category: 'Personal Growth', hint: 'Pauses, listening, and reflection'),
    Topic(id: 'pg20', title: 'The relationship between discipline and freedom', category: 'Personal Growth', hint: 'How structure creates space for creativity'),

    // Hypotheticals
    Topic(id: 'h1', title: 'If you could meet anyone in history, who and why?', category: 'Hypotheticals', hint: 'What would you ask them?'),
    Topic(id: 'h2', title: 'What would the world look like without the internet?', category: 'Hypotheticals', hint: 'Communication, commerce, and community'),
    Topic(id: 'h3', title: 'If you could live in any era, which would you choose?', category: 'Hypotheticals', hint: 'Consider the trade-offs carefully'),
    Topic(id: 'h4', title: 'What would you do as president for a day?', category: 'Hypotheticals', hint: 'Your top three priorities and why'),
    Topic(id: 'h5', title: 'If you could change one thing about society, what would it be?', category: 'Hypotheticals', hint: 'Be specific about the change and its ripple effects'),
    Topic(id: 'h6', title: 'What would happen if humans could live forever?', category: 'Hypotheticals', hint: 'Resources, motivation, and relationships'),
    Topic(id: 'h7', title: 'If you could have any superpower, what and why?', category: 'Hypotheticals', hint: 'How would you use it responsibly?'),
    Topic(id: 'h8', title: 'What if renewable energy replaced fossil fuels overnight?', category: 'Hypotheticals', hint: 'Economic shocks and geopolitical shifts'),
    Topic(id: 'h9', title: 'If animals could talk, what would they say to humans?', category: 'Hypotheticals', hint: 'Pick one animal and make it specific'),
    Topic(id: 'h10', title: 'What if sleep was no longer necessary?', category: 'Hypotheticals', hint: 'How would society change?'),
    Topic(id: 'h11', title: 'If you could redesign the education system, how?', category: 'Hypotheticals', hint: 'What would you keep, discard, and add?'),
    Topic(id: 'h12', title: 'What if there was no concept of money?', category: 'Hypotheticals', hint: 'How would humans exchange value?'),
    Topic(id: 'h13', title: 'If you could master any skill instantly, what would it be?', category: 'Hypotheticals', hint: 'And how would it change your life?'),
    Topic(id: 'h14', title: 'What would a world without social media look like?', category: 'Hypotheticals', hint: 'Connection, politics, and business'),
    Topic(id: 'h15', title: 'If every human was bilingual, how would the world change?', category: 'Hypotheticals', hint: 'Culture, diplomacy, and identity'),
    Topic(id: 'h16', title: 'What if you woke up tomorrow in a different country?', category: 'Hypotheticals', hint: 'How would you adapt and what would you miss?'),
    Topic(id: 'h17', title: 'If you could time travel, would you change anything?', category: 'Hypotheticals', hint: 'The butterfly effect and ethical dilemmas'),
    Topic(id: 'h18', title: 'What if cities were designed around pedestrians, not cars?', category: 'Hypotheticals', hint: 'Urban planning and quality of life'),
    Topic(id: 'h19', title: 'What if you had to give a TED talk tomorrow?', category: 'Hypotheticals', hint: 'What idea worth spreading would you choose?'),
    Topic(id: 'h20', title: 'If AI became sentient, how should we treat it?', category: 'Hypotheticals', hint: 'Rights, responsibilities, and ethics'),

    // Current Events
    Topic(id: 'ce1', title: 'The global response to climate change', category: 'Current Events', hint: 'Are governments doing enough?'),
    Topic(id: 'ce2', title: 'The rise of misinformation online', category: 'Current Events', hint: 'Causes, consequences, and solutions'),
    Topic(id: 'ce3', title: 'AI regulation: how should governments respond?', category: 'Current Events', hint: 'Innovation vs. safety balance'),
    Topic(id: 'ce4', title: 'The mental health crisis among young people', category: 'Current Events', hint: 'Contributing factors and systemic solutions'),
    Topic(id: 'ce5', title: 'The cost of living crisis', category: 'Current Events', hint: 'Causes, who is most affected, and policy responses'),
    Topic(id: 'ce6', title: 'Space exploration: private vs. government funding', category: 'Current Events', hint: 'SpaceX, NASA, and the future of space'),
    Topic(id: 'ce7', title: 'The impact of cryptocurrency on traditional finance', category: 'Current Events', hint: 'Disruption, speculation, and regulation'),
    Topic(id: 'ce8', title: 'Vaccine hesitancy and public health', category: 'Current Events', hint: 'Trust in science and institutions'),
    Topic(id: 'ce9', title: 'The future of democracy in the digital age', category: 'Current Events', hint: 'Disinformation, polarisation, and participation'),
    Topic(id: 'ce10', title: 'The global refugee crisis and shared responsibility', category: 'Current Events', hint: 'International law and humanitarian duty'),
    Topic(id: 'ce11', title: 'Nuclear energy: safe alternative or dangerous gamble?', category: 'Current Events', hint: 'New reactor technology vs. public perception'),
    Topic(id: 'ce12', title: 'Youth activism: is it making a difference?', category: 'Current Events', hint: 'Climate, gun control, and social justice movements'),
    Topic(id: 'ce13', title: 'The ethics of gene editing and designer babies', category: 'Current Events', hint: 'CRISPR and where we draw the line'),
    Topic(id: 'ce14', title: 'Big tech and the erosion of competition', category: 'Current Events', hint: 'Monopolies and antitrust regulation'),
    Topic(id: 'ce15', title: 'The future of global trade after COVID-19', category: 'Current Events', hint: 'Supply chain resilience and deglobalisation'),
    Topic(id: 'ce16', title: 'Mental health apps: helpful or harmful?', category: 'Current Events', hint: 'Accessibility vs. quality and data privacy'),
    Topic(id: 'ce17', title: 'How COVID-19 permanently changed society', category: 'Current Events', hint: 'Work, relationships, and institutions'),
    Topic(id: 'ce18', title: 'The role of NGOs in global development', category: 'Current Events', hint: 'Impact, accountability, and funding'),
    Topic(id: 'ce19', title: 'Gender identity in modern society', category: 'Current Events', hint: 'Law, rights, and cultural change'),
    Topic(id: 'ce20', title: 'China\'s role in global politics and economics', category: 'Current Events', hint: 'Belt and Road, trade tensions, and influence'),

    // Fun & Creative
    Topic(id: 'fc1', title: 'The best meal you\'ve ever had', category: 'Fun & Creative', hint: 'Describe it vividly — where, who, what made it special?'),
    Topic(id: 'fc2', title: 'Describe your perfect day from start to finish', category: 'Fun & Creative', hint: 'Be specific and paint a picture'),
    Topic(id: 'fc3', title: 'The most important invention of the 20th century', category: 'Fun & Creative', hint: 'Make your case and anticipate counterarguments'),
    Topic(id: 'fc4', title: 'Why travel is essential for personal growth', category: 'Fun & Creative', hint: 'Specific experiences that changed how you see the world'),
    Topic(id: 'fc5', title: 'The book or film that changed your life', category: 'Fun & Creative', hint: 'What idea or feeling did it leave you with?'),
    Topic(id: 'fc6', title: 'What would you put in a time capsule for 2075?', category: 'Fun & Creative', hint: 'What defines our era that future people should know?'),
    Topic(id: 'fc7', title: 'Why laughter is the best medicine', category: 'Fun & Creative', hint: 'Psychological and physiological benefits of humour'),
    Topic(id: 'fc8', title: 'The sport or hobby that shaped who you are', category: 'Fun & Creative', hint: 'Lessons beyond the activity itself'),
    Topic(id: 'fc9', title: 'What success means to you personally', category: 'Fun & Creative', hint: 'Beyond money and status'),
    Topic(id: 'fc10', title: 'The skill or talent you wish you had', category: 'Fun & Creative', hint: 'Why that one, and what would you do with it?'),
    Topic(id: 'fc11', title: 'What you would tell your 18-year-old self', category: 'Fun & Creative', hint: 'Be honest, be specific, be kind'),
    Topic(id: 'fc12', title: 'The place in the world that feels most like home', category: 'Fun & Creative', hint: 'What makes it special to you?'),
    Topic(id: 'fc13', title: 'A moment that completely changed your perspective', category: 'Fun & Creative', hint: 'Before and after — what shifted?'),
    Topic(id: 'fc14', title: 'What makes a city great to live in?', category: 'Fun & Creative', hint: 'Infrastructure, culture, community, or something else?'),
    Topic(id: 'fc15', title: 'The role of art and music in society', category: 'Fun & Creative', hint: 'Does art change minds or just reflect them?'),
    Topic(id: 'fc16', title: 'If you wrote a book, what would it be about?', category: 'Fun & Creative', hint: 'The central idea, the audience, and why now'),
    Topic(id: 'fc17', title: 'What makes a truly great leader?', category: 'Fun & Creative', hint: 'Use a real example to anchor your points'),
    Topic(id: 'fc18', title: 'The value of silence in a noisy world', category: 'Fun & Creative', hint: 'Mindfulness, creativity, and mental clarity'),
    Topic(id: 'fc19', title: 'What your favourite food says about you', category: 'Fun & Creative', hint: 'Have fun with this — use humour'),
    Topic(id: 'fc20', title: 'The kindest thing a stranger has ever done for you', category: 'Fun & Creative', hint: 'Details and reflection on what it meant'),

    // Business
    Topic(id: 'b1', title: 'Entrepreneurship: is it worth the risk?', category: 'Business', hint: 'Real costs beyond money — time, stress, relationships'),
    Topic(id: 'b2', title: 'Should companies adopt a 4-day work week?', category: 'Business', hint: 'Productivity data and employee wellbeing'),
    Topic(id: 'b3', title: 'Corporate social responsibility: genuine or PR?', category: 'Business', hint: 'When does ethics become marketing?'),
    Topic(id: 'b4', title: 'Work-life balance: myth or achievable reality?', category: 'Business', hint: 'Industry differences and individual responsibility'),
    Topic(id: 'b5', title: 'The importance of financial literacy for everyone', category: 'Business', hint: 'Why schools don\'t teach it and why they should'),
    Topic(id: 'b6', title: 'Startups vs established corporations: where should you work?', category: 'Business', hint: 'Career stage, risk tolerance, and learning'),
    Topic(id: 'b7', title: 'The future of retail in the age of e-commerce', category: 'Business', hint: 'Physical stores\' unique role'),
    Topic(id: 'b8', title: 'How advertising shapes our desires', category: 'Business', hint: 'Manipulation vs. information'),
    Topic(id: 'b9', title: 'Why diversity in leadership improves business performance', category: 'Business', hint: 'Evidence-based arguments'),
    Topic(id: 'b10', title: 'The gig economy: liberation or exploitation?', category: 'Business', hint: 'Flexibility from both sides of the equation'),

    // Environment
    Topic(id: 'e1', title: 'Individual actions vs systemic change for the climate', category: 'Environment', hint: 'Recycling vs. corporate accountability'),
    Topic(id: 'e2', title: 'Should single-use plastics be banned globally?', category: 'Environment', hint: 'Enforcement, alternatives, and developing nations'),
    Topic(id: 'e3', title: 'The future of sustainable fashion', category: 'Environment', hint: 'Fast fashion\'s environmental and human cost'),
    Topic(id: 'e4', title: 'The importance of biodiversity', category: 'Environment', hint: 'Why every species matters'),
    Topic(id: 'e5', title: 'Urban farming and the future of food security', category: 'Environment', hint: 'Vertical farms, rooftop gardens, local food'),
    Topic(id: 'e6', title: 'Food waste and its environmental impact', category: 'Environment', hint: 'Scale of the problem and practical solutions'),
    Topic(id: 'e7', title: 'Rewilding: restoring nature for the future', category: 'Environment', hint: 'Wolves in Yellowstone and lessons from rewilding projects'),
    Topic(id: 'e8', title: 'The link between poverty and environmental damage', category: 'Environment', hint: 'Who bears the burden of climate change?'),
    Topic(id: 'e9', title: 'The role of corporations in environmental protection', category: 'Environment', hint: 'Regulation vs. voluntary action'),
    Topic(id: 'e10', title: 'Green energy: nuclear vs. renewables debate', category: 'Environment', hint: 'Trade-offs in land use, cost, and reliability'),

    // Philosophy
    Topic(id: 'ph1', title: 'Can money buy happiness?', category: 'Philosophy', hint: 'Research on income, spending, and wellbeing'),
    Topic(id: 'ph2', title: 'Do we have free will?', category: 'Philosophy', hint: 'Determinism, neuroscience, and moral responsibility'),
    Topic(id: 'ph3', title: 'The ethics of eating meat', category: 'Philosophy', hint: 'Sentience, environment, and cultural tradition'),
    Topic(id: 'ph4', title: 'What is the meaning of life?', category: 'Philosophy', hint: 'Personal philosophy and different cultural answers'),
    Topic(id: 'ph5', title: 'Is social media making us more or less connected?', category: 'Philosophy', hint: 'Shallow connections vs. meaningful ones'),
    Topic(id: 'ph6', title: 'The value of privacy in the digital age', category: 'Philosophy', hint: 'Nothing to hide vs. freedom to be yourself'),
    Topic(id: 'ph7', title: 'Can artificial intelligence be conscious?', category: 'Philosophy', hint: 'What does consciousness even mean?'),
    Topic(id: 'ph8', title: 'Is it ever right to break the law?', category: 'Philosophy', hint: 'Civil disobedience and moral vs. legal obligation'),
    Topic(id: 'ph9', title: 'The ethics of humanitarian military intervention', category: 'Philosophy', hint: 'Sovereignty vs. the responsibility to protect'),
    Topic(id: 'ph10', title: 'What makes an action morally right?', category: 'Philosophy', hint: 'Consequentialism, deontology, and virtue ethics'),

    // Health
    Topic(id: 'hl1', title: 'The mental health benefits of regular exercise', category: 'Health', hint: 'Mood, anxiety, depression, and focus'),
    Topic(id: 'hl2', title: 'Should junk food be taxed like cigarettes?', category: 'Health', hint: 'Public health vs. personal freedom'),
    Topic(id: 'hl3', title: 'The link between sleep and productivity', category: 'Health', hint: 'What the science says about sleep debt'),
    Topic(id: 'hl4', title: 'Mindfulness: genuine practice or wellness trend?', category: 'Health', hint: 'Evidence-based benefits and commercial exploitation'),
    Topic(id: 'hl5', title: 'Public vs. private healthcare: which is better?', category: 'Health', hint: 'Access, quality, and funding models'),
    Topic(id: 'hl6', title: 'The benefits of spending time in nature', category: 'Health', hint: 'Physiological and psychological evidence'),
    Topic(id: 'hl7', title: 'Stress: the silent killer?', category: 'Health', hint: 'Modern sources of stress and how to manage them'),
    Topic(id: 'hl8', title: 'The role of community in individual wellbeing', category: 'Health', hint: 'Loneliness epidemic and social connection'),
    Topic(id: 'hl9', title: 'Nutrition myths that need to be debunked', category: 'Health', hint: 'Pick 2-3 common myths and address them'),
    Topic(id: 'hl10', title: 'Why young people are experiencing a mental health crisis', category: 'Health', hint: 'Social media, academic pressure, and uncertainty'),
  ];

  static List<String> get categories =>
      all.map((t) => t.category).toSet().toList()..sort();
}
